version: "3"

services:
    db:
        build:
            context: ./Database
            dockerfile: Dockerfile
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: letmein
            MYSQL_DATABASE: local
